/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
    application
    id("org.springframework.boot") version "3.2.4"
    id("io.spring.dependency-management") version "1.1.4"
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
    // Add the JitPack repository for LavaPlayer
    maven {
        url = uri("https://jitpack.io")
    }
    // Add Lavalink repository for YouTube implementation
    maven {
        url = uri("https://maven.lavalink.dev/releases")
    }
    // Add LavaSearch repository
    maven {
        url = uri("https://maven.topi.wtf/releases")
    }
    // Additional repositories that might be needed
    maven {
        url = uri("https://m2.dv8tion.net/releases")
    }
}

dependencies {
    // Spring Boot dependencies
    implementation("org.springframework.boot:spring-boot-starter-web")
    implementation("org.springframework.boot:spring-boot-starter-validation")
    
    // Lombok for boilerplate reduction
    compileOnly("org.projectlombok:lombok:1.18.30")
    annotationProcessor("org.projectlombok:lombok:1.18.30")
    
    // LavaPlayer dependencies
    implementation("com.github.walkyst:lavaplayer-fork:1.4.2")
    
    // YouTube source implementation
    implementation("dev.arbjerg.lavalink:youtube:4.0.0")
    
    // LavaSearch implementation - use specific version that's compatible
    implementation("dev.arbjerg.lavasearch:lavasearch:0.1.0")
    
    // Other audio dependencies that might be needed
    implementation("com.sedmelluq:lavaplayer-natives:1.3.14")
    implementation("com.sedmelluq:jda-nas:1.1.0")
    
    // Utility libraries
    implementation("org.apache.commons:commons-lang3:3.12.0")
    implementation("com.google.code.gson:gson:2.10.1")
    implementation("org.slf4j:slf4j-api:2.0.9")
    
    // Testing dependencies
    testImplementation("org.springframework.boot:spring-boot-starter-test")
    testImplementation("junit:junit:4.13.2")
}

group = "com.mjba"
version = "1.0-SNAPSHOT"
description = "soundify"
java.sourceCompatibility = JavaVersion.VERSION_17

application {
    mainClass.set("com.mjba.soundify.SoundifyApplication")
}

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

// Add configuration to fix Java 17 compatibility issues
tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
    options.compilerArgs.add("-parameters")
}

tasks.withType<Test> {
    useJUnitPlatform()
}
